### PR TITLE
fixed 17 and 4

### PR DESCRIPTION
**Pull request by TylerSadler**

### CODE REVIEW

**Comment by TylerSadler** [comment]
also just fixed issue 5

**Comment by TylerSadler** [comment]
fixed 6

**Comment by Andorbal** [comment]
This is too complex to merge.  I'd recommend creating a branch per issue so that you can create individual pull requests.

**Comment by TylerSadler** [comment]
thats fine. will cherry picking the commits where i fixed an issue to a new
branch work?

**Comment by Andorbal** [comment]
You could try that.  As long as each issue is in its own branch, that's all
that matters.

**Pull request closed without merging**
